apiVersion: v1
kind: Service
metadata:
  name: playinventoryservice-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
      # nodePort: 30003 #for external access
  selector:
    app: playinventoryservice