apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo2-deployment
  labels:
    app: mongo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo2
  template:
    metadata:
      labels:
        app: mongo2
    spec:
      containers:
        - name: mongo2
          image: mongo
          ports:
            - containerPort: 27017